# Generated by Django 2.2.7 on 2019-11-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
